# Generated by Django 2.0.1 on 2019-07-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='nome',
            field=models.CharField(default=1, help_text='Nome Da Empresa', max_length=100),
            preserve_default=False,
        ),
    ]
